# Generated by Django 4.2.7 on 2023-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_event_available_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(through='event_management.UserEventRegistration', to='event_management.users'),
        ),
    ]
